# Generated by Django 3.0.4 on 2020-05-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excuseTypes', '0006_auto_20200506_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled',
            name='prof',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='excuseTypes.Prof'),
        ),
    ]
