# Generated by Django 3.0.4 on 2020-05-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excuseTypes', '0008_auto_20200506_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='scheduled',
            name='prof',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
