# Generated by Django 3.0.4 on 2020-05-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excuseTypes', '0009_auto_20200506_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='emergency',
            name='prof',
            field=models.ForeignKey(default='Professor Pickle', on_delete=django.db.models.deletion.CASCADE, to='excuseTypes.Prof'),
        ),
    ]
